# Generated by Django 5.0.2 on 2025-04-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_budgetprediction_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('salary', 'Monthly Salary'), ('rental', 'Rental Income'), ('interest', 'Interest Received'), ('dividend', 'Dividend Income'), ('freelance', 'Freelance Income'), ('business', 'Business Income'), ('investment', 'Investment Returns'), ('gift', 'Gift Income'), ('other', 'Other Income')], default='salary', max_length=100),
        ),
    ]
